<a href="https://colab.research.google.com/github/HeatherAnnFoster/Bike-Assignment/blob/main/Heather_Foster's_Bike_df_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Section

In [5]:
import pandas as pd

In [6]:
df = pd.read_excel('/content/RailsToTrails_National Count Data_week - Total Count data (31 counters).xlsx')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Timeframe                   52 non-null     object
 1   Week of                     52 non-null     datetime64[ns]
 2    2019 counts (31 counters)  52 non-null     int64
 3    2020 counts (31 counters)  52 non-null     int64
 4   2021 Counts                 0 non-null      float64
 5   Change 2019-2020            52 non-null     float64
 6   Unnamed: 6                  52 non-null     float64
 7   Unnamed: 7                  0 non-null      float64
 8   Unnamed: 8                  1 non-null      float64
 9   Unnamed: 9                  1 non-null      float64
dtypes: datetime64[ns](1), float64(6), int64(2), object(1)
memory usage: 4.2+ KB

In [8]:
df.head()

,Timeframe,Week of,2019 counts (31 counters),2020 counts (31 counters),2021 Counts,Change 2019-2020,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Week 1,2019-12-30,167679,183546,NaN,0.09,1.094627,NaN,NaN,NaN
1,Week 2,2020-01-06,82340,97140,NaN,0.18,117.974253,NaN,NaN,NaN
2,Week 3,2020-01-13,62315,75782,NaN,0.22,121.611169,NaN,NaN,NaN
3,Week 4,2020-01-20,75801,83809,NaN,0.11,110.564504,NaN,NaN,NaN
4,Week 5,2020-01-27,75841,94738,NaN,0.25,124.916602,NaN,NaN,NaN

In [9]:
After_July = df['Week of'] >= '2020-07-31'
df[After_July]

,Timeframe,Week of,2019 counts (31 counters),2020 counts (31 counters),2021 Counts,Change 2019-2020,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
31,Week 32,2020-08-03,180605,239827,NaN,0.33,132.790897,NaN,NaN,NaN
32,Week 33,2020-08-10,191450,219279,NaN,0.15,114.535910,NaN,NaN,NaN
33,Week 34,2020-08-17,168754,241007,NaN,0.43,142.815578,NaN,NaN,NaN
34,Week 35,2020-08-24,176624,273677,NaN,0.55,154.948931,NaN,NaN,NaN
35,Week 36,2020-08-31,184806,227918,NaN,0.23,123.328247,NaN,NaN,NaN
36,Week 37,2020-09-07,157345,207670,NaN,0.32,131.983857,NaN,NaN,NaN
37,Week 38,2020-09-14,152527,207320,NaN,0.36,135.923476,NaN,NaN,NaN
38,Week 39,2020-09-21,141072,207918,NaN,0.47,147.384314,NaN,NaN,NaN
39,Week 40,2020-09-28,135881,186004,NaN,0.37,136.887424,NaN,NaN,NaN
40,Week 41,2020-10-05,132239,182924,NaN,0.38,138.328330,NaN,NaN,NaN
41,Week 42,2020-10-12,110816,159246,NaN,0.44,143.703075,NaN,NaN,NaN
42,Week 43,2020-10-19,110761,141404,NaN,0.28,127.665875,NaN,NaN,NaN
43,Week 44,2020-10-26,109795,147907,NaN,0.35,134.711963,NaN,NaN,NaN
44,Week 45,2020-11-02,109766,154502,NaN,0.41,140.755790,NaN,NaN,NaN
45,Week 46,2020-11-09,86824,155805,NaN,0.79,179.449231,NaN,NaN,NaN
46,Week 47,2020-11-16,88122,97835,NaN,0.11,111.022219,NaN,NaN,NaN
47,Week 48,2020-11-23,72380,101036,NaN,0.40,139.591047,NaN,NaN,NaN
48,Week 49,2020-11-30,81871,84123,NaN,0.03,102.750669,NaN,NaN,NaN
49,Week 50,2020-12-07,68364,92126,NaN,0.35,134.758060,NaN,NaN,NaN
50,Week 51,2020-12-14,58063,73188,NaN,0.26,126.049291,NaN,NaN,NaN
51,Week 52,2020-12-21,71890,69962,NaN,-0.03,97.318125,NaN,26.73,0.514016

In [10]:
#Find how many entries occured after July 31, 2022.  Hint: use len(df_filtered) to get the length of the dataframe.

len(df[After_July])

21

In [11]:
Weeks_Needed_df = df[After_July]

In [12]:
#Select just data where the "change 2019-2020" column is greater than 50% (greater than .5)
percentage_change = df["Change 2019-2020"] > 0.5
df["Change 2019-2020"] > 0.5

0     False
1     False
2     False
3     False
4     False
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16    False
17     True
18    False
19     True
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33    False
34     True
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45     True
46    False
47    False
48    False
49    False
50    False
51    False
Name: Change 2019-2020, dtype: bool

In [13]:
len(df["Change 2019-2020"] > 0.5)

52

In [14]:
#Put these together!
#When filtering you can use & to combine two filters.
#Determine how many weeks in the second half of the year (after July 31, 2020) also had a change greater than 50%?  Hint:use len().
df[(After_July) & (percentage_change)]

,Timeframe,Week of,2019 counts (31 counters),2020 counts (31 counters),2021 Counts,Change 2019-2020,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
34,Week 35,2020-08-24,176624,273677,NaN,0.55,154.948931,NaN,NaN,NaN
45,Week 46,2020-11-09,86824,155805,NaN,0.79,179.449231,NaN,NaN,NaN

In [15]:
len(df[(After_July) & (percentage_change)])

2

In [16]:
#Next, make a new filter where you only include changes greater than 100% that also occured after July 31, 2020.
#Display that filtered DataFRame.
#Were there any weeks in the second half of the year (After July 31, 2020) where the change was grater than 100%?
#Hint:  IF you only see column headers with no data, this means no rows met both conditions.

After_July & df ["Change 2019-2020"] > 1
df[(After_July) & (df ["Change 2019-2020"] > 1)]

Empty DataFrame
Columns: [Timeframe, Week of,  2019 counts (31 counters),  2020 counts (31 counters), 2021 Counts, Change 2019-2020, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9]
Index: []